# Generated by Django 4.1.5 on 2023-02-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image1',
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='Image2',
        ),
    ]
