# Generated by Django 4.1.5 on 2023-02-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_images_image1_rename_image_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='webapp/static/images')),
                ('image', models.ImageField(upload_to='webapp/static/image')),
            ],
        ),
        migrations.DeleteModel(
            name='Image1',
        ),
        migrations.DeleteModel(
            name='Image2',
        ),
    ]
