# Generated by Django 4.1.5 on 2023-02-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_image_delete_image1_delete_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='path1',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='path2',
        ),
    ]
