# Generated by Django 4.1.5 on 2023-02-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_images_image_path1_rename_image_image_path2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
    ]
